### ISSUE TITLE
怎么增加2000年之前的时间

### ISSUE THREAD

**Issue by booboom** [weijhfly/rolldate#14]
![image](https://user-images.githubusercontent.com/24515720/54676299-60c22280-4b3b-11e9-8650-e077e7a706f7.png)
最早就2000年了，我要做出生年月的选择，不能都是00后啊。求解决。

**Comment by booboom** [comment]
@weijhfly 
大佬

**Comment by booboom** [comment]
问题已经解决，在下图
![image](https://user-images.githubusercontent.com/24515720/54679507-6a9b5400-4b42-11e9-8f78-4327a1395da7.png)
位置修改beginYear就行了

**Comment by weijhfly** [comment]
不是在源码改的，new rolldate.Date(）这里初始化的
