### ISSUE TITLE
这里有设置时间范围的参数吗？

### ISSUE THREAD

**Issue by tanghaichen** [weijhfly/rolldate#17]
就比如我需要选择两个时间，当我选择一个时间之后，另一个只能选择这个时间之后的时间，此类的方法。。emmm

**Comment by weijhfly** [comment]
不支持。但你可以在第一个时间选择后，设置第二个时间打开时的默认值，如：

`
document.getElementById('date2').date = new Date('2019/03/29')；
`

当用户点击确定按钮后，通过confirmBefore判断选择的时间是否在可选范围，如果不是，return false并做出提示让用户重新选择。
这样体验略差一些，不过在当前的插件版本里是可行的。
