### ISSUE TITLE
目前已知问题及待完善

### ISSUE THREAD

**Issue by weijhfly** [weijhfly/rolldate#2]
1，插件启动时默认跳转至之前的日期，但如果之前的日期无效(包含时分或时分秒格式中偶现)，插件将报错而无法使用，待修复。
2，插件滑动时，偶发滑动位置不准确，待解决。
3，包含年月日格式的，滑动结束时会重新计算天数，如之前的30天，现在28天，可能会出现28天后面还能滑动的bug。
4，为了使操作更便利，将模仿mobiscroll(日期位置贴近屏幕下方)，增加另外一种界面风格。
5，扩展月、日、时分、时分秒这四种格式。
6，在某些低版本的安卓uc浏览器中，插件出现明显错误(重要)。
7,  rolldate依赖了iscroll解决滑动问题，但iscroll不够稳定，小概率出现滑动位置不对齐，待解决。

**Comment by weijhfly** [comment]
1，已解决，将YYYY-MM-DD替换为YYYY/MM/DD.

**Comment by weijhfly** [comment]
2、3，已基本解决

**Comment by weijhfly** [comment]
5，6已解决，4，暂不实现

**Comment by gsZhiZunBao** [comment]
iphone点击触发时 会有卡顿一下 然后再跳出时间选择框 不知道作者有没有遇到过

**Comment by weijhfly** [comment]
@gsZhiZunBao 应该是click事件的300ms延迟吧？可以用fastclick插件解决
