### ISSUE TITLE
大佬，这个插件能实现循环滚动嘛？

### ISSUE THREAD

**Issue by 821484451** [weijhfly/rolldate#20]
面对小时的选择，60hour需要一个一个翻，体验不是太好

**Comment by weijhfly** [comment]
依赖的better-scroll插件不支持，所以不打算实现

**Comment by 821484451** [comment]
你这个是1.14版本，better-scroll现在又1.15版本了，它里面有一个snap的参数，大佬能帮忙看看利用这个可以实现嘛

**Comment by weijhfly** [comment]
@821484451 snap我知道，不是1.15版本才有的。snap是结合轮播使用的，我测试wheel中设置snap发现各种问题

**Comment by 821484451** [comment]
好吧
