### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by wlpgdq** [weijhfly/rolldate#4]
在angular.js中用new rolldate.Date()，f12出现这个，时间选择界面出不来。
[Deprecation] 'webkitCancelAnimationFrame' is vendor-specific. Please use the standard 'cancelAnimationFrame' instead.
stop @ rolldate.js:8
scrollTo @ rolldate.js:8
scrollToElement @ rolldate.js:8
value @ rolldate.js:8
(anonymous) @ rolldate.js:8
n @ ionic.bundle.min.js:22
t @ ionic.bundle.min.js:22
l @ ionic.bundle.min.js:22
请问这个是怎么问题？

**Comment by wlpgdq** [comment]
可以用了，引入时未注意，需要引入rolldate.css和rolldate.js，好像引入rolldate.js的时候需要加type="text/javascript"，不过还是非常感谢作者的，比心，哈哈

**Comment by gaoyiyang** [comment]
请问可以用鼠标滚轮选取吗？

**Comment by weijhfly** [comment]
@gaoyiyang 使用鼠标滚轮滑动？better-scroll支持滚轮，但引入滚轮会增加插件大小，且似乎没多少必要，所以没打算增加此功能

**Comment by gaoyiyang** [comment]
好的，谢谢




------------------ 原始邮件 ------------------
发件人: "雾空"<notifications@github.com>;
发送时间: 2019年4月23日(星期二) 晚上9:48
收件人: "weijhfly/rolldate"<rolldate@noreply.github.com>;
抄送: "高一洋"<370625414@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [weijhfly/rolldate] 问题 (#4)




@gaoyiyang 使用鼠标滚轮滑动？better-scroll支持滚轮，但引入滚轮会增加插件大小，且似乎没多少必要，所以没打算增加此功能
