### ISSUE TITLE
有时候会生成两次rolldate-container.导致不能使用，有什么解决办法？

### ISSUE THREAD

**Issue by wlpgdq** [weijhfly/rolldate#5]
![1](https://user-images.githubusercontent.com/29969309/45335305-4cf89b00-b5b1-11e8-90a2-daa4673f9532.png)

**Comment by weijhfly** [comment]
这种情况应该是一个dom元素绑定了两次插件，正常点击时初始化一次，取消时销毁，是不会出现两次的

**Comment by wlpgdq** [comment]
怎么销毁呢？

**Comment by weijhfly** [comment]
new rolldate.Date({
 	el:'#date',
		format:'YYYY-MM',
		beginYear:2000,
		endYear:2100
 })
 new rolldate.Date({
 	el:'#date',
		format:'YYYY-MM',
		beginYear:2000,
		endYear:2100
 })
请检查一下代码，有没有同一个dom选择器调用了两次插件，如上#date

**Comment by Leafykn** [comment]
我也遇到了这种问题，但是并没有重复绑定

**Comment by Leafykn** [comment]
确实，如果上一次的注册没有销毁，再次注册点击时间控件的时候，会出现这个问题

**Comment by weijhfly** [comment]
@Leafykn 
 _this.iscroll.forEach(function(v,i){v.destroy();})
document.body.removeChild(_this.$('.rolldate-container')[0]);
销毁是插件自动执行的，每次点击确定、取消、遮罩层都必定会执行，然后点击输入框时，
document.body.appendChild(‘.rolldate-container’)dom生成一次，除了重复绑定，我暂时还想不到其他原因，可否贴上相关代码

**Comment by Leafykn** [comment]
> @Leafykn
> _this.iscroll.forEach(function(v,i){v.destroy();})
> document.body.removeChild(_this.$('.rolldate-container')[0]);
> 销毁是插件自动执行的，每次点击确定、取消、遮罩层都必定会执行，然后点击输入框时，
> document.body.appendChild(‘.rolldate-container’)dom生成一次，除了重复绑定，我暂时还想不到其他原因，可否贴上相关代码

是这里的问题
new rolldate.Date({
                    el: '#leave-date',
                    format: 'YYYY-MM-DD hh:mm',
                    confirmBefore: (el, date) => {
                        this.leaveT = date;
                    }
                });
跟你上面说的一样，可能就是某个操作导致重复new 多次。没有相应的方法去销毁这个对象，但是直接销毁这个dom元素可以做到，连带注册的对象一起销毁了

**Comment by Leafykn** [comment]
> @Leafykn
> _this.iscroll.forEach(function(v,i){v.destroy();})
> document.body.removeChild(_this.$('.rolldate-container')[0]);
> 销毁是插件自动执行的，每次点击确定、取消、遮罩层都必定会执行，然后点击输入框时，
> document.body.appendChild(‘.rolldate-container’)dom生成一次，除了重复绑定，我暂时还想不到其他原因，可否贴上相关代码

没有相应的方法去销毁这个对象

**Comment by wlpgdq** [comment]
我这边的解决方法是第二次绑定时判断第一次绑定的是否还存在，如果存在，就不要在绑定，不存在则在绑定一次😂😂😂😂

**Comment by weijhfly** [comment]
后续会增加判断，重复绑定将无效
