### ISSUE TITLE
Uncaught TypeError: Cannot read property 'previousSibling' of undefined

### ISSUE THREAD

**Issue by Ale-cc** [weijhfly/rolldate#7]
rolldate.js:formatted:224 Uncaught TypeError: Cannot read property 'previousSibling' of undefined
    at t.value (rolldate.js:formatted:224)
    at HTMLInputElement.<anonymous> (rolldate.js:formatted:128)
![image](https://user-images.githubusercontent.com/18302674/45671701-ba2fa180-bb58-11e8-82c0-69054f224a50.png)
Dom元素放template里，Vue(1.0版本)组件create时候初始化组件，结果createui报错。
![image](https://user-images.githubusercontent.com/18302674/45672377-8eadb680-bb5a-11e8-8e97-3f6157c93bb4.png)
![image](https://user-images.githubusercontent.com/18302674/45672474-d7fe0600-bb5a-11e8-8483-8bcba11bf356.png)

**Comment by weijhfly** [comment]
年份这一栏似乎没有创建成功，不好定位问题，可否把这一页的代码发给我

**Comment by weijhfly** [comment]
旧版不再维护
