### ISSUE TITLE
没有默认日期的参数吗？

### ISSUE THREAD

**Issue by rason560** [weijhfly/rolldate#9]
如题，貌似没找到可以设置默认日期的选项

**Comment by rason560** [comment]
另外，希望如果input value里面有值的话，希望插件弹出的时候可以显示value里对应的日期值。

**Comment by rason560** [comment]
再提一个体验上的问题，感觉UI的面积小。手机上操作滚动的精度不好控制，有时候会滑动的太过，总是选不中要选的日期

**Comment by weijhfly** [comment]
document.getElementById('date').date = new Date('2017/9/6');可以这样设置一个默认日期，有时分秒的可以2017/9/6 23:28:19这样，在考虑要不要做成一个配置

**Comment by weijhfly** [comment]
ui问题后续有打算修改，增加类似mui日期的界面，另外插件几乎不受样式影响，你可以修改为自己想要的

**Comment by rason560** [comment]
> document.getElementById('date').date = new Date('2017/9/6');可以这样设置一个默认日期，有时分秒的可以2017/9/6 23:28:19这样，在考虑要不要做成一个配置

我觉得很有必要做成可配置，这个功能很多日期插件都具有且很常用。可以参考laydate。
